import { Application } from "express";
import { Module } from "module";
import { Config } from "../config";


export default class TheoryModule extends Module {
    register(app: Application): void {

        // Matching
        app.post("/Theory/Matching", function(req, res) {

            // Get the Request Data
            var jsonString = '';

            req.on('data', function (data) {
                
                // Store the Request Data
                jsonString += data;
            });

            req.on('end', function () {

                // Error Handling if it's null
                if(!(jsonString))
                {
                    jsonString = '{}';
                }

                // Parse the JSON
                let jsonData: any = JSON.parse(jsonString);

                // Response Data
                let resParams = {
                    status_code: "0",

                    // Server Status
                    // 0 = Offline
                    // 1 = Online
                    server_status : 1,

                    rival_data: {
                        auto_match: [
                            {
                                id: 999999996,
                                name: "ＧＵＥＳＴ１",
                                grade: 11,
                                powerhouseLv: 1,
                                mytitleId: 0,
                                country: 9,
                                auraId: 0,
                                auraColor: 0,
                                auraLine: 0,
                                roundRanking: 0,
                                storeName: Config.getConfig().shopName,
                                sex: 1,
                                face: 91,
                                eye: 265,
                                mouth: 13,
                                hair: 369,
                                glasses: 0,
                                faceAccessory: 0,
                                body: 113,
                                bodyAccessory: 0,
                                behind: 0,
                                bg: 1,
                                effect: 0,
                                special: 0,
                                styleCarId: 131337,
                                color: 6,
                                bureau: 6202,
                                kana: 10,
                                sNo: 33,
                                lNo: 3892,
                                tuneLv: 16,
                                carFlag: 2102306,
                                tunePoint: 0,
                                infinityTune: 0,
                                tuneParts: 131068,
                                partsList: [-65536, -65535, -65512, -48128, -47104, -46848, -45056, -39936, -38912, -38656, -36864, -33792, -31744, -31488, -31232, -29696, -29440, -27648, -26368, -24576, -23296, -22272, -22016, -2016, -1],
                                partsCount: 0,
                                stamp0: 0,
                                stamp1: 1,
                                stamp2: 2,
                                stamp3: 3,
                                attack: 123,
                                defense: 119,
                                safety: 135,
                                runaway: 127,
                                trickFlg: 0,
                                taEval: 9
                            },
                            {
                                id: 999999997,
                                name: "ＧＵＥＳＴ２",
                                grade: 9,
                                powerhouseLv: 1,
                                mytitleId: 0,
                                country: 9,
                                auraId: 0,
                                auraColor: 0,
                                auraLine: 0,
                                roundRanking: 0,
                                storeName: Config.getConfig().shopName,
                                sex: 0,
                                face: 1,
                                eye: 1,
                                mouth: 1,
                                hair: 1,
                                glasses: 0,
                                faceAccessory: 0,
                                body: 1,
                                bodyAccessory: 0,
                                behind: 0,
                                bg: 6,
                                effect: 0,
                                special: 0,
                                styleCarId: 131586,
                                color: 1,
                                bureau: 1905,
                                kana: 24,
                                sNo: 57,
                                lNo: 8760,
                                tuneLv: 16,
                                carFlag: 86594133,
                                tunePoint: 0,
                                infinityTune: 0,
                                tuneParts: 131068,
                                partsList: [-65536, -48128, -47104, -46848, -46080, -45056, -44800, -39936, -39680, -38912, -38656, -37888, -36864, -33792, -31744, -31488, -31232, -29696, -29440, -27648, -26368, -24576, -23296, -22272, -22016, -16640, -2016, -768, -1, -65536, -65518, -48128, -47872, -47104, -46848, -45056, -39936, -38912, -38656, -37888, -36864, -33792, -31744, -31488, -31232, -29696, -29440, -27648, -26368, -24576, -23296, -22272, -22016, -2016, -768, -1],
                                partsCount: 0,
                                stamp0: 0,
                                stamp1: 1,
                                stamp2: 2,
                                stamp3: 3,
                                attack: 127,
                                defense: 127,
                                safety: 127,
                                runaway: 127,
                                trickFlg: 0,
                                taEval: 0
                            },
                            {
                                id: 999999998,
                                name: "ＧＵＥＳＴ３",
                                grade: 6,
                                powerhouseLv: 1,
                                mytitleId: 0,
                                country: 9,
                                auraId: 0,
                                auraColor: 0,
                                auraLine: 0,
                                roundRanking: 0,
                                storeName: Config.getConfig().shopName,
                                sex: 1,
                                face: 91,
                                eye: 265,
                                mouth: 13,
                                hair: 387,
                                glasses: 0,
                                faceAccessory: 0,
                                body: 114,
                                bodyAccessory: 0,
                                behind: 0,
                                bg: 1,
                                effect: 0,
                                special: 0,
                                styleCarId: 0,
                                color: 0,
                                bureau: 6202,
                                kana: 28,
                                sNo: 58,
                                lNo: 170,
                                tuneLv: 16,
                                carFlag: 2118679,
                                tunePoint: 0,
                                infinityTune: 0,
                                tuneParts: 131068,
                                partsList: [-65536, -48128, -47104, -46848, -46080, -45056, -44800, -39936, -39680, -38912, -38656, -36864, -33792, -31744, -31488, -31232, -29696, -29440, -27648, -26368, -24576, -23296, -22272, -22016, -2016, -768, -1],
                                partsCount: 0,
                                stamp0: 0,
                                stamp1: 1,
                                stamp2: 2,
                                stamp3: 3,
                                attack: 127,
                                defense: 127,
                                safety: 127,
                                runaway: 127,
                                trickFlg: 0,
                                taEval: 0
                            },
                            {
                                id: 999999999,
                                name: "ＧＵＥＳＴ４",
                                grade: 4,
                                powerhouseLv: 1,
                                mytitleId: 0,
                                country: 9,
                                auraId: 0,
                                auraColor: 0,
                                auraLine: 0,
                                roundRanking: 0,
                                storeName: Config.getConfig().shopName,
                                sex: 1,
                                face: 91,
                                eye: 265,
                                mouth: 13,
                                hair: 369,
                                glasses: 0,
                                faceAccessory: 0,
                                body: 113,
                                bodyAccessory: 0,
                                behind: 0,
                                bg: 1,
                                effect: 0,
                                special: 0,
                                styleCarId: 5,
                                color: 0,
                                bureau: 1900,
                                kana: 42,
                                sNo: 533,
                                lNo: 8292,
                                tuneLv: 16,
                                carFlag: 2122018,
                                tunePoint: 0,
                                infinityTune: 0,
                                tuneParts: 131068,
                                partsList: [-65536, -65530, -48128, -47104, -46848, -45056, -39936, -38912, -38656, -36864, -33792, -31744, -31488, -31232, -29696, -29440, -28672, -27648, -26368, -24576, -23296, -22272, -22016, -2016, -768, -1],
                                partsCount: 24,
                                stamp0: 0,
                                stamp1: 1,
                                stamp2: 2,
                                stamp3: 3,
                                attack: 128,
                                defense: 128,
                                safety: 128,
                                runaway: 128,
                                trickFlg: 0,
                                taEval: 0
                            }
                        ],
                        power_match: [
                            {
                                id: 999999995,
                                name: "ＳＵＰＥＲ１",
                                grade: 37,
                                powerhouseLv: 1,
                                mytitleId: 902,
                                country: 9,
                                auraId: 0,
                                auraColor: 0,
                                auraLine: 2,
                                roundRanking: 0,
                                storeName: Config.getConfig().shopName,
                                sex: 0,
                                face: 1,
                                eye: 1,
                                mouth: 1,
                                hair: 1,
                                glasses: 0,
                                faceAccessory: 7,
                                body: 3,
                                bodyAccessory: 0,
                                behind: 0,
                                bg: 84,
                                effect: 0,
                                special: 0,
                                styleCarId: 65548,
                                color: 6,
                                bureau: 901,
                                kana: 27,
                                sNo: 330,
                                lNo: 4966,
                                tuneLv: 16,
                                carFlag: 102837282,
                                tunePoint: 0,
                                infinityTune: 0,
                                tuneParts: 131068,
                                partsList: [
                                    -50180096,
                                    2114147072,
                                    -39856,
                                    -38912,
                                    -36864,
                                    -31488,
                                    -31232,
                                    -29440,
                                    -28672,
                                    -27648,
                                    -26368,
                                    -24576,
                                    -23296,
                                    -22272,
                                    -37888,
                                    -37886,
                                    -48128,
                                    -29696,
                                    -46848,
                                    -38656,
                                    -39936,
                                    -31740,
                                    -48126,
                                    -47102,
                                    -29694,
                                    -46846,
                                    -38654,
                                    -39934,
                                    -39678,
                                    -29953,
                                    -33790,
                                    -65532
                                ],
                                partsCount: 34,
                                stamp0: 0,
                                stamp1: 1,
                                stamp2: 2,
                                stamp3: 3,
                                attack: 127,
                                defense: 127,
                                safety: 127,
                                runaway: 127,
                                trickFlg: 0,
                                taEval: 0
                            },
                            {
                                id: 999999994,
                                name: "ＳＵＰＥＲ２",
                                grade: 37,
                                powerhouseLv: 1,
                                mytitleId: 4392,
                                country: 9,
                                auraId: 0,
                                auraColor: 0,
                                auraLine: 2,
                                roundRanking: 0,
                                storeName: Config.getConfig().shopName,
                                sex: 1,
                                face: 138,
                                eye: 326,
                                mouth: 13,
                                hair: 662,
                                glasses: 0,
                                faceAccessory: 0,
                                body: 114,
                                bodyAccessory: 0,
                                behind: 0,
                                bg: 100,
                                effect: 0,
                                special: 0,
                                styleCarId: 65548,
                                color: 3,
                                bureau: 1900,
                                kana: 14,
                                sNo: 333,
                                lNo: 8606,
                                tuneLv: 16,
                                carFlag: 2173986,
                                tunePoint: 0,
                                infinityTune: 0,
                                tuneParts: 131068,
                                partsList: [
                                    -65525,
                                    -48128,
                                    -47104,
                                    -46848,
                                    -45056,
                                    -39936,
                                    -38656,
                                    -37888,
                                    -36864,
                                    -33792,
                                    -33790,
                                    -33279,
                                    -31744,
                                    -31488,
                                    -31232,
                                    -29696,
                                    -29440,
                                    -29439,
                                    -27648,
                                    -26368,
                                    -24576,
                                    -23296,
                                    -22272,
                                    -22016,
                                    -2016,
                                    -768,
                                    -1,
                                    -1,
                                    -1,
                                    -1,
                                    -1,
                                    -1
                                ],
                                partsCount: 26,
                                stamp0: 0,
                                stamp1: 1,
                                stamp2: 2,
                                stamp3: 3,
                                attack: 127,
                                defense: 127,
                                safety: 127,
                                runaway: 127,
                                trickFlg: 0,
                                taEval: 0
                            },
                            {
                                id: 999999993,
                                name: "ＳＵＰＥＲ３",
                                grade: 29,
                                powerhouseLv: 1,
                                mytitleId: 4392,
                                country: 9,
                                auraId: 0,
                                auraColor: 0,
                                auraLine: 1,
                                roundRanking: 0,
                                storeName: Config.getConfig().shopName,
                                sex: 0,
                                face: 1,
                                eye: 1,
                                mouth: 1,
                                hair: 6,
                                glasses: 9,
                                faceAccessory: 60,
                                body: 4,
                                bodyAccessory: 0,
                                behind: 0,
                                bg: 91,
                                effect: 0,
                                special: 0,
                                styleCarId: 1286,
                                color: 6,
                                bureau: 1900,
                                kana: 23,
                                sNo: 36,
                                lNo: 2457,
                                tuneLv: 16,
                                carFlag: 488707618,
                                tunePoint: 0,
                                infinityTune: 0,
                                tuneParts: 131068,
                                partsList: [
                                    -48128,
                                    -46848,
                                    -45056,
                                    -38912,
                                    -38656,
                                    -36864,
                                    -31744,
                                    -31488,
                                    -31232,
                                    -29696,
                                    -29440,
                                    -29436,
                                    -27648,
                                    -26368,
                                    -24576,
                                    -23296,
                                    -22272,
                                    -22016,
                                    -16640,
                                    -2016,
                                    -37886,
                                    -29183,
                                    -33785,
                                    -33279,
                                    -65515,
                                    -25588,
                                    -47103,
                                    -766,
                                    -39934,
                                    -1,
                                    -1,
                                    -1
                                ],
                                partsCount: 29,
                                stamp0: 188,
                                stamp1: 1,
                                stamp2: 2,
                                stamp3: 3,
                                attack: 123,
                                defense: 123,
                                safety: 131,
                                runaway: 123,
                                trickFlg: 0,
                                taEval: 0
                            }
                        ]
                    }
                }
    
                // Send the response to the client
                res.send(resParams);
            });
        });
    }
}